// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/*
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhOL9Xhyi4p61tnxqFu64fxjCVIIAcT78',
    appId: '1:595195865155:android:0f187ec37f8f3e86cf4cf6',
    messagingSenderId: '595195865155',
    projectId: 'syriasell-35510',
    storageBucket: 'syriasell-35510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHywigBvmPIZIg1vZjD2WM5pwnhiVBvOA',
    appId: '1:595195865155:ios:d76b366eda4a8a04cf4cf6',
    messagingSenderId: '595195865155',
    projectId: 'syriasell-35510',
    storageBucket: 'syriasell-35510.firebasestorage.app',
    iosBundleId: 'com.syriasell.syriaSell',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJa66j4pbJVojwTNHe2FemTQWkmkOi5Ss',
    appId: '1:595195865155:web:a4fd2be7e02ff2a4cf4cf6',
    messagingSenderId: '595195865155',
    projectId: 'syriasell-35510',
    authDomain: 'syriasell-35510.firebaseapp.com',
    storageBucket: 'syriasell-35510.firebasestorage.app',
    measurementId: 'G-TY5LQ74ZJF',
  );

}
 */
