platform :ios, '13.0'

# تعطيل إحصائيات CocoaPods
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# استخدام الـ frameworks (مطلوب لبعض البودات)
use_frameworks!

target 'Runner' do
  # Pods for Runner
  # Flutter plugin pods سيتم تثبيتها تلقائيًا عند تشغيل pod install
end
