name: Build iOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Generate iOS files
      run: flutter create --platforms=ios .
    
    - name: Build iOS
      run: flutter build ios --no-codesign
